"""drop upvot_asssociation table

Revision ID: 23fa464b1923
Revises: 2dc2ccf1bfda
Create Date: 2023-11-03 23:59:52.501565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23fa464b1923'
down_revision = '2dc2ccf1bfda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upvote_association')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upvote_association',
    sa.Column('user_id', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('event_id', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('vote_text', mysql.VARCHAR(length=256), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='upvote_association_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='upvote_association_ibfk_2'),
    sa.PrimaryKeyConstraint('user_id', 'event_id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('upvote_association', schema=None) as batch_op:
        batch_op.create_index('ix_upvote_association_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_upvote_association_event_id', ['event_id'], unique=False)

    # ### end Alembic commands ###
