"""Deleted some columns

Revision ID: 2b0d5d437d7b
Revises: 50d93a6cb2b1
Create Date: 2022-12-29 23:28:04.244113

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b0d5d437d7b'
down_revision = '50d93a6cb2b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('secondary_color_argb')
        batch_op.drop_column('main_color_argb')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_color_argb', mysql.VARCHAR(length=8), nullable=True))
        batch_op.add_column(sa.Column('secondary_color_argb', mysql.VARCHAR(length=8), nullable=True))

    # ### end Alembic commands ###
