"""added votes, gender and price fix

Revision ID: 2dc2ccf1bfda
Revises: 51261ea00405
Create Date: 2023-11-03 23:49:43.215351

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2dc2ccf1bfda'
down_revision = '51261ea00405'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('gender')

    op.create_table('association',
    sa.Column('member_id', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('events_id', mysql.VARCHAR(length=8), nullable=False),
    sa.ForeignKeyConstraint(['events_id'], ['events.id'], name='association_ibfk_2'),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], name='association_ibfk_1'),
    sa.PrimaryKeyConstraint('member_id', 'events_id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('association', schema=None) as batch_op:
        batch_op.create_index('ix_association_member_id', ['member_id'], unique=False)
        batch_op.create_index('ix_association_events_id', ['events_id'], unique=False)

    op.create_table('upvote_association',
    sa.Column('user_id', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('event_id', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('vote_text', mysql.VARCHAR(length=256), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='upvote_association_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='upvote_association_ibfk_2'),
    sa.PrimaryKeyConstraint('user_id', 'event_id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('upvote_association', schema=None) as batch_op:
        batch_op.create_index('ix_upvote_association_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_upvote_association_event_id', ['event_id'], unique=False)

    # ### end Alembic commands ###
