"""nullable columns in users table

Revision ID: 50d93a6cb2b1
Revises: 14e5637dbded
Create Date: 2022-12-29 08:10:45.914310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50d93a6cb2b1'
down_revision = '14e5637dbded'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('nickname',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('surname',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('surname',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('nickname',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###
